config/routes.rb
Rails.application.routes.draw do
  root "static_pages#home"

  get "sessions/new"
  get "/help", to: "static_pages#help"
  get "/about", to: "static_pages#about"
  get "/contact", to: "static_pages#contact"
  get "/signup", to: "users#new"
  get "/login", to: "sessions#new"
  get "/login", to: "sessions#create"

  post "/login", to: "sessions#create"

  delete "/logout", to: "sessions#destroy"

  scope "(:locale)", locale: /en|vi/ do
    resources :microposts
    resources :users
    resources :account_activations, only: :edit
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/user.rb
class User < ApplicationRecord
  attr_accessor :remember_token, :activation_token

  before_save :downcase_email
  before_create :create_activation_digest

  scope :activated, where activated: FILL_IN

  VALID_EMAIL_REGEX = Settings.user.emailRegex

  validates :name, presence: true, length: {maximum: Settings.user.maxName}
  validates :email, presence: true, length: {maximum: Settings.user.maxEmail},
    format: {with: VALID_EMAIL_REGEX}, uniqueness: {case_sensitive: false}
  validates :password, presence: true, length: {minimum: Settings.user.minPass, allow_nil: true}

  has_secure_password
  class << self
    def digest string
      cost = ActiveModel::SecurePassword.min_cost ? BCrypt::Engine::MIN_COST : BCrypt::Engine.cost
      BCrypt::Password.create string, cost: cost
    end

    def new_token
      SecureRandom.urlsafe_base64
    end
  end

  def remember
    self.remember_token = User.new_token
    update remember_digest: User.digest(remember_token)
  end

  def authenticated? attribute, token
    digest = send "#{attribute}_digest"
    return false if digest.nil?
    BCrypt::Password.new(digest).is_password? token
  end

  def forget
    update :remember_digest, nil
  end

  def activate
    update activated: FILL_IN, activated_at: FILL_IN
  end

  def send_activation_email
    UserMailer.account_activation(self).deliver_now
  end

  private:
    def downcase_email
      email.downcase!
    end

    def create_activation_digest
      self.activation_token  = User.new_token
      self.activation_digest = User.digest activation_token
    end
end

app/controllers/account_activations_controller.rb
class AccountActivationsController < ApplicationController
  def edit
    user = User.find_by email: params[:email]
    if user && !user.activated? && user.authenticated?(:activation, params[:id])
      user.activate
      log_in user
      flash[:success] = t "controller.concerns.account.success"
      redirect_to user
    else
      flash[:danger] = t "controller.concerns.account.danger"
      redirect_to root_pth
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  include SessionsHelper

  before_action :set_locale

  private
  def set_locale
    I18n.locale = params[:locale] || I18n.default_locale
  end

  def default_url_options
    {locale: I18n.locale}
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new; end

  def create
    user = User.find_by email: params[:session][:email].downcase
    if user&.authenticate(params[:session][:password])
      if user.activated?
        log_in user
        params[:session][:remember_me] == "1" ? remember(user) : forget(user)
        redirect_back_or user
      else
        message = t "controller.concern.session_controller.message"
        message += t "controller.concern.session_controller.mess"
        flash[:warning] = message
        redirect_to root_url
      end
    else
      flash.now[:danger] = t "controller.concerns.session_controller.danger"
      render :new
    end
  end

  def destroy
    log_out if logged_in?
    redirect_to root_path
  end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home; end

  def help; end

  def contact; end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :load_user, except: %i(new create index)
  before_action :logged_in_user, except: %i(new create show)
  before_action :correct_user, only: %i(edit update)
  before_action :admin_user, only: :destroy

  def show
    return unless FILL_IN
  end

  def new
    @user = User.new
  end

  def index
    @users = User.activated.page(params[:page]).per Settings.user.per
  end

  def create
    @user = User.new user_params
    if @user.save
      @user.send_activation_email
      flash[:info] = t "controller.concerns.user.activate"
      redirect_to root_path
    else
      render :new
    end
  end

  def edit; end

  def update
    if @user.update user_params
      flash[:success] = t "controller.concerns.user.updated"
      redirect_to @user
    else
      render :edit
    end
  end

  def destroy
    if @user.destroy
      flash[:success] = t "controller.concerns.user.deleted"
      redirect_to users_path
    else
      render :show
  end

  private

    def user_params
      params.require(:user).permit :name, :email, :password, :password_confirmation
    end

    def logged_in_user
      return if logged_in?
      store_location
      flash[:danger] = t "controller.concerns.user.login"
      redirect_to login_path
    end

    def correct_user
      redirect_to root_path unless current_user? @user
    end

    def admin_user
      redirect_to(root_path) unless current_user.admin?
    end

    def load_user
      @user = User.find_by id: params[:id]
      return if @user
      flash[:danger] = t("controllers.user.not_exits")
      redirect_to root_path
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def full_title page_title = ""
    base_title = t "controller.helpers.application.base"
    if page_title.empty?
      base_title
    else
      page_title + " | " + base_title
    end
  end
end

app/helpers/sessions_helper.rb
module SessionsHelper
  def log_in user
    session[:user_id] = user.id
  end

  def remember user
    user.remember
    cookies.permanent.signed[:user_id] = user.id
    cookies.permanent[:remember_token] = user.remember_token
  end

  def current_user? user
    user == current_user
  end

  def current_user
    if user_id = session[:user_id]
      @current_user ||= User.find_by id: user_id
    elsif user_id = cookies.signed[:user_id]
      user = User.find_by id: user_id
      if user&.authenticated?(:remember, cookies[:remember_token])
        log_in user
        @current_user = user
      end
    end
  end

  def logged_in?
    current_user.present?
  end

  def forget user
    user.forget
    cookies.delete :user_id
    cookies.delete :remember_token
  end

  def log_out
    forget current_user
    session.delete :user_id
    @current_user = nil
  end

  def redirect_back_or default
    redirect_to(session[:forwarding_url] || default)
    session.delete(:forwarding_url)
  end

  def store_location
    session[:forwarding_url] = request.original_url if request.get?
  end
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
  def gravatar_for user, size: Settings.user.usersHelper.gravatarSize
    gravatar_id = Digest::MD5::hexdigest user.email.downcase
    gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}?s=#{size}"
    image_tag gravatar_url, alt: user.name, class: "gravatar"
  end
end

app/views/layouts/_footer.html.erb
<footer class="footer">
  <small>
    <%= t "layouts._footer.the" %> <%= link_to t("layouts._footer.tutorial"), Settings.client.railstutorial %>
    <%= link_to t("layouts._footer.michael"), Settings.client.michael %>
  </small>
  <nav>
    <ul>
      <li><%= link_to t("layouts._footer.about"), about_path %></li>
      <li><%= link_to t("layouts._footer.contact"), contact_path %></li>
      <li><%= link_to t("layouts._footer._new"), Settings.client.newTutorial %></li>
    </ul>
  </nav>
</footer>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
  <div class="container">
    <%= link_to t("layouts._header.name"), root_path, id: "logo" %>
    <nav>
      <ul class="nav navbar-nav navbar-right">
        <li><%= link_to t("layouts._header.home"), root_path %></li>
        <li><%= link_to t("layouts._header.help"), help_path %></li>
        <% if logged_in? %>
          <li><%= link_to t("layouts._header.users"), users_path %></li>
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown"><%= t("layouts._header.account") %><b class="caret"></b>
            </a>
            <ul class="dropdown-menu">
              <li><%= link_to t("layouts._header.profile"), current_user %></li>
              <li><%= link_to t("layouts._header.settings"), edit_user_path( current_user) %></li>
              <li class="divider"></li>
              <li>
                <%= link_to t("layouts._header.logout"), logout_path, method: :delete %>
              </li>
            </ul>
          </li>
        <% else %>
          <li><%= link_to t("layouts._header.login"), login_path %></li>
        <% end %>
      </ul>
    </nav>
  </div>
</header>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
  <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
  </script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= full_title yield(:title) %></title>
    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag "application", media: "all","data-turbolinks-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbolinks-track": "reload" %>
    <%= render "layouts/shim" %>
  </head>
  <body>
    <%= link_to t("layouts.application.en"), locale:"en" %>
    <%= link_to t("layouts.application.vi"), locale:"vi" %>
    <%= render "layouts/header" %>
    <div class="container">
      <% flash.each do |message_type, message| %>
        <%= content_tag(:div, message, class: "alert alert-#{message_type}") %>
      <% end %>
      <%= yield %>
      <%= render "layouts/footer" %>
    </div>
  </body>
</html>

app/views/shared/_error_messages.html.erb
<% if @user.errors.any? %>
  <div id="error_explanation">
    <div class="alert alert-danger">
      <%= t "shared.errorMessage" %>
      <%= pluralize @user.errors.count, "error" %>.
    </div>
    <ul>
    <% @user.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

app/views/static_pages/....html.erb
<h1>StaticPages#...</h1>
<p>Find me in app/views/static_pages/....html.erb</p>

app/views/static_pages/about.html.erb
<h1><%= t "static_pages.aboutPage.about" %></h1>

app/views/static_pages/contact.html.erb
<% provide :title, t("static_pages.contactPage.contact") %>
<h1><%= t "static_pages.contactPage.contact" %></h1>
<p>
  <%= t "static_pages.contactPage.header" %>
  <%= link_to t("static_pages.contactPage.contactpage"), Settings.client.contact %>.
</p>

app/views/static_pages/help.html.erb
<h1><%= t "static_pages.helppage.help" %></h1>
<p>
  <%= t "static_pages.helppage.getHelp" %>
  <%= link_to t("static_pages.helppage.tutorialHelp"), Settings.client.railstutorial %>.
  <%= t "static_pages.helppage.helpApp" %>
  <% link_to Settings.client.railsBook do %>
    <%= t "static_pages.helppage.tutorial" %>
  <% end %>
  <%= t "static_pages.helppage.book" %>
</p>

app/views/static_pages/home.html.erb
<div class="center jumbotron">
  <h1><%= t "static_pages.home.welcome" %></h1>
  <h2>
    <%= t "static_pages.home.homepage" %>
    <%= link_to t("static_pages.home.rubyTutorial"), Settings.client.railstutorial %>
    <%= t "static_pages.home.sampleApp" %>.
  </h2>
  <%= link_to t("static_pages.home.signup"), signup_path, class: "btn btn-lg btn-primary" %>
  <img src="./assets/images/rails.png"  alt="Rails logo"/>
</div>

app/views/users/_form.html.erb
<%= form_for @user do |f| %>
  <%= render "shared/error_messages", object: @user %>

  <%= f.label t("user._form.name") %>
  <%= f.text_field :name, class: "form-control" %>

  <%= f.label t("user._form.email") %>
  <%= f.email_field :email, class: "form-control" %>

  <%= f.label t("user._form.password") %>
  <%= f.password_field :password, class: "form-control" %>

  <%= f.label t("user._form.confirm") %>
  <%= f.password_field :password_confirmation, class: "form-control" %>

  <%= f.submit yield(:button_text), class: "btn btn-primary" %>
<% end %>

app/views/users/_user.html.erb
<li>
  <%= gravatar_for user, size: Settings.user.gravatar_forU %>
  <%= link_to user.name, user %>
    <% if current_user.admin? && !current_user? user %>
    | <%= link_to t("user._user.delete"), user, method: :delete, data: { confirm: t("user._user.sure") } %>
  <% end %>
</li>

app/views/users/edit.html.erb
<% provide :title, t("user.edit.editU") %>
<% provide :button_text, t("user.edit.save") %>
<h1><%= t "user.edit._update" %></h1>
<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= render "form" %>
    <div class="gravatar_edit">
      <%= gravatar_for @user %>
      <%= link_to t("user.edit.change"), Settings.user.mail %>
    </div>
  </div>
</div>

app/views/users/index.html.erb
<% provide :title, t("user.index.all") %>
<h1><%= t "user.index.all" %></h1>
<ul class="users">
  <% @users.each do |user| %>
    <%= render @users %>
  <% end %>
  <%= paginate @users %>
</ul>

app/views/users/new.html.erb
<% provide :title, t("user.new.signup") %>
<% provide :button_text, t("user.new.create") %>
<h1><%= t "user.new.signup" %></h1>
<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= render "form" %>
  </div>
</div>

app/views/users/show.html.erb
<% provide :title, @user.name %>
<div class="row">
  <aside class="col-md-4">
    <section class="user_info">
      <h1>
        <%= gravatar_for @user %>
        <%= @user.name %>
      </h1>
    </section>
  </aside>
</div>